version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5431:5432
    volumes:
      - postgres_data
    networks:
      - app_network
    env_file:
      - docker/postgres.env

volumes:
  postgres_data:


networks:
  app_network:


