version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5431:5432
    volumes:
      - postgres_data
    networks:
      - app_network
    env_file:
      - docker/postgres.env

  fusion_db:
    container_name: fusion_auth_db
    image: postgres:latest
    env_file:
      - ./docker/fusion-auth.env
    volumes:
      - fusion_db_data:/var/lib/postgresql/data
    ports:
      - 5430:5432
    restart: unless-stopped
    networks:
      - fusion_auth_network

  fusion-auth:
    container_name: fusion-auth
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - fusion_db
    env_file:
      - ./docker/fusion-auth.env
    networks:
      - fusion_auth_network
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: unless-stopped
    hostname: rabbit-local
    volumes:
      - ./docker/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/data/dev/rabbit:/var/lib/rabbitmq/mnesia/
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app_network

  elastic_setup:
    container_name: elastic_setup
    build:
      context: ./docker/elastic_setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - elastic_setup:/state:Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elastic_network
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./docker/elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./docker/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - elastic_network

  kibana:
    container_name: kibana
    build:
      context: ./docker/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./docker/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro,z
      - kibana_data:/usr/share/kibana/data:z
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elastic_network
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  fusion_db_data:
  fa_config:
  elastic_setup:
  elasticsearch:
  kibana_data:


networks:
  app_network:
  fusion_auth_network:
    driver: bridge
  elastic_network:
    driver: bridge
